/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'masahito' at '13/12/23 21:53' with Gradle 1.10
 *
 * @author masahito, @date 13/12/23 21:53
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
